POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "testperson",
    "number": 12341
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dan Abramov",
    "number": 1234123
}